name: Cron on Docker Hub

on:
  schedule:
    - cron: '59 23 * * 4'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      # Check out the repo
      - name: Check out the repo
        uses: actions/checkout@v3
      # Login
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Get repository name
      - name: Get repository name
        id: get_repo_name
        run: echo ::set-output name=REPO_NAME::${GITHUB_REPOSITORY#*/}
      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.get_repo_name.outputs.REPO_NAME }}:latest
